### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by insecurejezza** [Quorafind/Obsidian-Memos#3]
It would be great to know if mobile support is possible, or will it be limited to desktop given the way it is coded?

**Comment by Quorafind** [comment]
no, i think it can be used on mobile, maybe some bugs there need to fixed

**Comment by Quorafind** [comment]
Should be fixed in 1.0.5

**Comment by insecurejezza** [comment]
I’m still getting an error when trying to load the mobile version. Could it be due to a plugin conflict?

![13DD0C59-1CBC-4174-9C0E-5565040EA50B](https://user-images.githubusercontent.com/70424851/148296751-ae6c87fa-a2ca-49e6-adc9-14957f032a59.jpeg)

**Comment by insecurejezza** [comment]
Tested with a clean vault but not working. OS is iOS 15

**Comment by Quorafind** [comment]
It is werid , I will try to debug it on my iOS

**Comment by FelipeRearden** [comment]
> It is werid , I will try to debug it on my iOS

This info about the mobile version might be helpful 🙏 

![image](https://user-images.githubusercontent.com/85180696/148307526-a576d59d-c54f-464b-ba6e-ea5ae0afdc22.jpeg)

**Comment by Quorafind** [comment]
fixed in #20

**Comment by FelipeRearden** [comment]
Hello @Quorafind !!!!

Just to let you know that I linked this issue with the plugin Carry-Foward because it does not work on iOS as well :(

Since the Carry-Forward developer @jglev uses Android my idea is to help giving information that could help to understand what is happening on iOS :)

Please @Quorafind , if you have any insight that might help @jglev to understand why this is happening in Carry-Forward plugin, I would be extremely grateful to you :) 🙏 


Thanks and have a great day!

**Comment by psychsatani** [comment]
> I’m still getting an error when trying to load the mobile version. Could it be due to a plugin conflict?
> 
> ![13DD0C59-1CBC-4174-9C0E-5565040EA50B](https://user-images.githubusercontent.com/70424851/148296751-ae6c87fa-a2ca-49e6-adc9-14957f032a59.jpeg)

I am still getting this. I am on the latest updates of ios, obsidian app and memos plugin.

**Comment by Quorafind** [comment]
Seems you didn't install the version 1.1.9, try it and see if the issue remain

**Comment by psychsatani** [comment]
I am on latest version. 1.1.9 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/78266798/148868304-d8c48880-939a-4e54-8a29-a258479ae925.png">

**Comment by Quorafind** [comment]
It's wierd, could you try to install the test plugin from shabegom, and log the console to let me find out what happened? Here is the link of the plugin: https://github.com/shabegom/obsidian-mobile-logging

**Comment by psychsatani** [comment]
[error] Plugin failure: obsidian-memos Error: The file “main.js” couldn’t be opened because there is no such file. 
[log]  
[log]

**Comment by psychsatani** [comment]
Should I delete everything and install all files manually instead of using BRAT plugin?

**Comment by Quorafind** [comment]
It's so weird that I did use brat on iOS to install it... Maybe the problem is main.js weren't installed correctly

**Comment by psychsatani** [comment]
I deleted the plugin folder and installed manually on Mac. Then waited for it to sync. Both Mac and iOS have 1.1.10, the Mac plugin runs as expected but the above issue persists with iOS.

**Comment by Quorafind** [comment]
Could you try to disable some plugins to check if there is a confict?

**Comment by psychsatani** [comment]
I did another fresh install from Mac, synced it using obsidian sync, disabled all other plugins including BRAT on iphone, no difference.

**Comment by Quorafind** [comment]
Maybe I need the review from Licat to see where remain errors.

**Comment by psychsatani** [comment]
I am on the latest update of memos and obsidian insider build. Dunno which of these fixed it but it is finally fixed. Thank you 🙏
